repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.10
      exclude: dacbench/envs/fast-downward
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
- repo: https://github.com/PyCQA/pydocstyle
    rev: master
    hooks:
      - id: pydocstyle
        exclude: 'dacbench/envs/rl-plan/*'
