[project]
name = "DACBench"
version = "0.0.1"
description = "A benchmark library for DAC"
authors = [
    "Theresa Eimer <eimer@tnt.uni-hannover.de>"
]
license = "Apache 2.0"
readme = "README.md"
python = "^3.6"
homepage = "https://github.com/automl/DACBench"
repository = "https://github.com/automl/DACBench"
documentation = "https://github.com/automl/DACBench"

keywords = ["DAC", "Dynamic Algorithm Configuration", "HPO"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Natural Language :: English",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
]

[install_requires]
gym = "0.15.3"
numpy = "1.18.0"
scipy = "1.4.1"
cma = "2.7"
pandas = "1.0.3"
matplotlib = "3.1.3"
seaborn = "0.11"

[dev-dependencies]
black = "20.8b1"
scikit-learn = "0.23.2"
flake8 = "3.8.4"
pytest = "6"
pytest-cov = "2"
pre-commit = "2.7.1"

[example-dependencies]
chainerrl = "0.7.0"
ray = "1.0.0"
tensorflow = "1.14"
dm-tree = "0.1.5"
opencv-python = "4.2.0.32"
stable-baselines = "2.10.1"

[build-system]
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3",
    "toml",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::UserWarning",
    "ignore::DeprecationWarning",
]
testpaths = ["tests"]

[tool.coverage.run]
omit = ["dacbench/envs/fast-downward/*"]

[tool.coverage.html]
directory = "coverage_report"

[tool.black]
line-length = 88
target_version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | dacbench/envs/fast-downward
  )/
)
'''
